-- =============================================================================
-- MindLog — Migration 003: Medications adherence log refactor
-- Decouples medication_adherence_logs from daily_entries so patients can log
-- adherence independently (not just during check-in).
-- =============================================================================

-- 1. Make daily_entry_id nullable — medication adherence no longer requires a
--    concurrent check-in session. The link is preserved when logging during
--    check-in but is not mandatory.
ALTER TABLE medication_adherence_logs
  ALTER COLUMN daily_entry_id DROP NOT NULL;

-- 2. Drop the old unique constraint that included daily_entry_id.
--    The constraint name is auto-generated by Postgres; cover both naming styles.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'medication_adherence_logs_daily_entry_id_patient_medication_id_key'
  ) THEN
    ALTER TABLE medication_adherence_logs
      DROP CONSTRAINT medication_adherence_logs_daily_entry_id_patient_medication_id_key;
  END IF;
END $$;

-- 3. New unique constraint: one adherence log per medication per calendar day.
--    This is the natural uniqueness rule for daily medication tracking.
ALTER TABLE medication_adherence_logs
  ADD CONSTRAINT uq_med_adherence_medication_date
  UNIQUE (patient_medication_id, entry_date);

-- 4. Composite index for efficient "today's meds" queries
CREATE INDEX IF NOT EXISTS idx_med_adherence_patient_med_date
  ON medication_adherence_logs (patient_id, patient_medication_id, entry_date DESC);
