-- =============================================================================
-- MindLog — Migration 007: OMOP CDM person_id sequential assignment
-- Creates assign_omop_person_ids() function that grants stable OMOP person_ids
-- to patients who have given data_research consent. Intended to be called by
-- the nightly population snapshot worker before generating each snapshot.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Function: assign_omop_person_ids()
-- Idempotent: safe to call repeatedly. Returns count of newly assigned IDs.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION assign_omop_person_ids()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  next_id  BIGINT;
  assigned INTEGER := 0;
  p        RECORD;
BEGIN
  -- Determine the next available sequential OMOP person_id
  SELECT COALESCE(MAX(omop_person_id), 0) + 1
  INTO next_id
  FROM patients;

  -- Eligible patients: active data_research consent, no OMOP person_id yet.
  -- ORDER BY id ensures deterministic assignment across multiple calls.
  FOR p IN
    SELECT DISTINCT ON (pa.id) pa.id
    FROM patients pa
    JOIN consent_records cr
      ON cr.patient_id = pa.id
     AND cr.consent_type = 'data_research'
     AND cr.granted = TRUE
    WHERE pa.omop_person_id IS NULL
    ORDER BY pa.id
  LOOP
    -- Double-checked update to guard against concurrent execution
    UPDATE patients
    SET omop_person_id = next_id
    WHERE id = p.id
      AND omop_person_id IS NULL;

    IF FOUND THEN
      next_id  := next_id + 1;
      assigned := assigned + 1;
    END IF;
  END LOOP;

  RETURN assigned;
END;
$$;

COMMENT ON FUNCTION assign_omop_person_ids() IS
  'Assigns sequential OMOP CDM person_ids to patients with active data_research '
  'consent who do not yet have an OMOP person_id. Idempotent; returns count of '
  'newly assigned IDs. Call this at the start of the nightly population snapshot '
  'worker or via the trigger below.';

-- ---------------------------------------------------------------------------
-- Trigger: auto-assign OMOP person_ids before each population snapshot insert.
-- If your snapshot is generated by an application worker, you can call
-- assign_omop_person_ids() directly at the start of the worker instead.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION trg_fn_omop_assign_before_snapshot()
RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
  PERFORM assign_omop_person_ids();
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION trg_fn_omop_assign_before_snapshot() IS
  'Trigger function: calls assign_omop_person_ids() before each row is inserted '
  'into population_snapshots, ensuring all newly consenting patients receive an '
  'OMOP person_id before the snapshot is written.';

-- Attach trigger only if it doesn't already exist (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger
    WHERE tgname  = 'trg_omop_assign_before_snapshot'
      AND tgrelid = 'population_snapshots'::regclass
  ) THEN
    CREATE TRIGGER trg_omop_assign_before_snapshot
      BEFORE INSERT ON population_snapshots
      FOR EACH ROW
      EXECUTE FUNCTION trg_fn_omop_assign_before_snapshot();
  END IF;
END;
$$;

-- ---------------------------------------------------------------------------
-- View: omop_person_map — convenience view for data warehouse exports
-- Maps MindLog patient UUIDs → OMOP person_ids for consented patients.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW omop_person_map AS
  SELECT
    p.id            AS patient_id,
    p.omop_person_id,
    p.research_cohort,
    p.primary_icd10_code,
    p.created_at    AS mindlog_created_at
  FROM patients p
  WHERE p.omop_person_id IS NOT NULL;

COMMENT ON VIEW omop_person_map IS
  'Maps MindLog patient UUIDs to OMOP CDM person_ids for export to the OMOP '
  'common data model. Only includes patients with assigned person_ids (i.e., '
  'those who have given data_research consent).';

-- ---------------------------------------------------------------------------
-- Grant: allow the snapshot worker role to call the function (adjust role name)
-- ---------------------------------------------------------------------------

-- GRANT EXECUTE ON FUNCTION assign_omop_person_ids() TO mindlog_worker;
-- Commented out — uncomment and adjust role name to match your deployment.
